import type { Sector } from "./types";

export const SECTOR_NAV: Record<Sector, { href: string; label: string; group?: string }[]> = {
  captacao: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/captacao", label: "Captação" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/comunicacao", label: "Comunicação" },
    { href: "/admin/ponto", label: "Ponto" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  marketing: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/atendimento", label: "Atendimento" },
    { href: "/admin/marketing", label: "Marketing" },
    { href: "/admin/integracoes", label: "Integrações" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/comunicacao", label: "Comunicação" },
    { href: "/admin/ponto", label: "Ponto" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  administrativo: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/atendimento", label: "Atendimento" },
    { href: "/admin/captacao", label: "Captação" },
    { href: "/admin/marketing", label: "Marketing" },
    { href: "/admin/administrativo", label: "Imóveis" },
    { href: "/admin/proprietarios", label: "Proprietários" },
    { href: "/admin/corretores", label: "Corretores" },
    { href: "/admin/clientes", label: "Clientes" },
    { href: "/admin/aprovacoes", label: "Aprovações" },
    { href: "/admin/juridico", label: "Jurídico" },
    { href: "/admin/leads", label: "Leads" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/financeiro-imovel", label: "Financ. Imóvel" },
    { href: "/admin/financeiro-empresarial", label: "Financ. Empresa" },
    { href: "/admin/financeiro-empresarial#comissoes", label: "Comissões" },
    { href: "/admin/alugueis", label: "Aluguéis" },
    { href: "/admin/comunicacao", label: "Comunicação" },
    { href: "/admin/ponto", label: "Ponto" },
    { href: "/admin/notificacoes", label: "Notificações" },
    { href: "/admin/auditoria", label: "Auditoria" },
  ],
  juridico: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/atendimento", label: "Atendimento" },
    { href: "/admin/juridico", label: "Jurídico" },
    { href: "/admin/clientes", label: "Clientes" },
    { href: "/admin/alugueis", label: "Aluguéis" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/comunicacao", label: "Comunicação" },
    { href: "/admin/ponto", label: "Ponto" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  recepcao: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/atendimento", label: "Atendimento" },
    { href: "/admin/consulta-imoveis", label: "Imóveis" },
    { href: "/admin/leads", label: "Leads" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/comunicacao", label: "Comunicação" },
    { href: "/admin/ponto", label: "Ponto" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  financeiro: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/atendimento", label: "Atendimento" },
    { href: "/admin/financeiro-imovel", label: "Financ. Imóvel" },
    { href: "/admin/financeiro-empresarial", label: "Financ. Empresa" },
    { href: "/admin/financeiro-empresarial#comissoes", label: "Comissões" },
    { href: "/admin/alugueis", label: "Aluguéis" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/comunicacao", label: "Comunicação" },
    { href: "/admin/ponto", label: "Ponto" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  aluguel: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/atendimento", label: "Atendimento" },
    { href: "/admin/alugueis", label: "Aluguéis" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/comunicacao", label: "Comunicação" },
    { href: "/admin/ponto", label: "Ponto" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  admin_central: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/atendimento", label: "Atendimento" },
    { href: "/admin/captacao", label: "Captação" },
    { href: "/admin/marketing", label: "Marketing" },
    { href: "/admin/administrativo", label: "Imóveis" },
    { href: "/admin/proprietarios", label: "Proprietários" },
    { href: "/admin/corretores", label: "Corretores" },
    { href: "/admin/clientes", label: "Clientes" },
    { href: "/admin/aprovacoes", label: "Aprovações" },
    { href: "/admin/juridico", label: "Jurídico" },
    { href: "/admin/leads", label: "Leads" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/financeiro-imovel", label: "Financ. Imóvel" },
    { href: "/admin/financeiro-empresarial", label: "Financ. Empresa" },
    { href: "/admin/financeiro-empresarial#comissoes", label: "Comissões" },
    { href: "/admin/alugueis", label: "Aluguéis" },
    { href: "/admin/relatorios", label: "Relatórios" },
    { href: "/admin/comunicacao", label: "Comunicação" },
    { href: "/admin/ponto", label: "Ponto" },
    { href: "/admin/movimentacoes", label: "Movimentações" },
    { href: "/admin/notificacoes", label: "Notificações" },
    { href: "/admin/usuarios", label: "Usuários" },
    { href: "/admin/auditoria", label: "Auditoria" },
  ],
};
