import type { Sector } from "./types";

export const SECTOR_NAV: Record<Sector, { href: string; label: string; group?: string }[]> = {
  captacao: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/captacao", label: "Captação" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  marketing: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/marketing", label: "Marketing" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  administrativo: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/captacao", label: "Captação" },
    { href: "/admin/marketing", label: "Marketing" },
    { href: "/admin/administrativo", label: "Imóveis" },
    { href: "/admin/proprietarios", label: "Proprietários" },
    { href: "/admin/aprovacoes", label: "Aprovações" },
    { href: "/admin/juridico", label: "Jurídico" },
    { href: "/admin/contratos", label: "Contratos" },
    { href: "/admin/leads", label: "Leads" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/financeiro-imovel", label: "Financ. Imóvel" },
    { href: "/admin/comissoes", label: "Comissões" },
    { href: "/admin/financeiro-empresarial", label: "Financ. Empresa" },
    { href: "/admin/notificacoes", label: "Notificações" },
    { href: "/admin/auditoria", label: "Auditoria" },
  ],
  juridico: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/juridico", label: "Jurídico" },
    { href: "/admin/contratos", label: "Contratos" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  recepcao: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/leads", label: "Leads" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  financeiro: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/financeiro-imovel", label: "Financ. Imóvel" },
    { href: "/admin/comissoes", label: "Comissões" },
    { href: "/admin/financeiro-empresarial", label: "Financ. Empresa" },
    { href: "/admin/notificacoes", label: "Notificações" },
  ],
  admin_central: [
    { href: "/admin", label: "Dashboard" },
    { href: "/admin/captacao", label: "Captação" },
    { href: "/admin/marketing", label: "Marketing" },
    { href: "/admin/administrativo", label: "Imóveis" },
    { href: "/admin/proprietarios", label: "Proprietários" },
    { href: "/admin/aprovacoes", label: "Aprovações" },
    { href: "/admin/juridico", label: "Jurídico" },
    { href: "/admin/contratos", label: "Contratos" },
    { href: "/admin/leads", label: "Leads" },
    { href: "/admin/agenda", label: "Agenda" },
    { href: "/admin/financeiro-imovel", label: "Financ. Imóvel" },
    { href: "/admin/comissoes", label: "Comissões" },
    { href: "/admin/financeiro-empresarial", label: "Financ. Empresa" },
    { href: "/admin/notificacoes", label: "Notificações" },
    { href: "/admin/usuarios", label: "Usuários" },
    { href: "/admin/auditoria", label: "Auditoria" },
    { href: "/admin/configuracoes", label: "Configurações" },
  ],
};
